[project]
name = "git-helper"
version = "0.1.0"
description = "Interactive command line helper for Git workflows"
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Christopher Hirschauer"}]

[project.scripts]
git-helper = "git_helper.cli:main"
